// Code generated by "stringer -type=Family -output=family.strings.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownFamily-0]
	_ = x[IntegerFamily-1]
	_ = x[BooleanFamily-2]
	_ = x[TextFamily-3]
	_ = x[ArrayFamily-4]
	_ = x[OIDFamily-5]
	_ = x[ObjectFamily-6]
	_ = x[DescriptorFamily-7]
}

const _Family_name = "UnknownFamilyIntegerFamilyBooleanFamilyTextFamilyArrayFamilyOIDFamilyObjectFamilyDescriptorFamily"

var _Family_index = [...]uint8{0, 13, 26, 39, 49, 60, 69, 81, 97}

func (i Family) String() string {
	if i >= Family(len(_Family_index)-1) {
		return "Family(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Family_name[_Family_index[i]:_Family_index[i+1]]
}
